# serverless.yml
component: nuxtjs # (必填) 组件名称，此处为 nuxtjs
name: apex-community-server-website # (必填) 实例名称
org: Kong # (可选) 用于记录组织信息，默认值为您的腾讯云账户 APPID
app: ACSWeb # (可选) 该 nuxt.js 项目名称
stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs10.15
  functionConf:
    timeout: 10
    memorySize: 128
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
  staticConf:
    cosConf:
      # 这里是创建的 COS 桶名称
      bucket: acs-web-1259477301